from django.db import models
from genres.models import Genre

NATIONALITY_CHOICES = (
    ("AFG", "Afeganistão"),
    ("ALB", "Albânia"),
    ("DEU", "Alemanha"),
    ("AND", "Andorra"),
    ("AGO", "Angola"),
    ("ATG", "Antígua e Barbuda"),
    ("SAU", "Arábia Saudita"),
    ("DZA", "Argélia"),
    ("ARG", "Argentina"),
    ("ARM", "Armênia"),
    ("AUS", "Austrália"),
    ("AUT", "Áustria"),
    ("AZE", "Azerbaijão"),
    ("BHS", "Bahamas"),
    ("BHR", "Bahrein"),
    ("BGD", "Bangladesh"),
    ("BRB", "Barbados"),
    ("BEL", "Bélgica"),
    ("BLZ", "Belize"),
    ("BEN", "Benim"),
    ("BLR", "Bielorrússia"),
    ("MMR", "Mianmar"),
    ("BOL", "Bolívia"),
    ("BIH", "Bósnia e Herzegovina"),
    ("BWA", "Botsuana"),
    ("BRA", "Brasil"),
    ("BRN", "Brunei"),
    ("BGR", "Bulgária"),
    ("BFA", "Burkina Faso"),
    ("BDI", "Burundi"),
    ("BTN", "Butão"),
    ("CPV", "Cabo Verde"),
    ("CMR", "Camarões"),
    ("KHM", "Camboja"),
    ("CAN", "Canadá"),
    ("QAT", "Catar"),
    ("KAZ", "Cazaquistão"),
    ("TCD", "Chade"),
    ("CHL", "Chile"),
    ("CHN", "China"),
    ("CYP", "Chipre"),
    ("COL", "Colômbia"),
    ("COM", "Comores"),
    ("COG", "Congo"),
    ("PRK", "Coreia do Norte"),
    ("KOR", "Coreia do Sul"),
    ("CIV", "Costa do Marfim"),
    ("CRI", "Costa Rica"),
    ("HRV", "Croácia"),
    ("CUB", "Cuba"),
    ("DNK", "Dinamarca"),
    ("DJI", "Djibuti"),
    ("DMA", "Dominica"),
    ("EGY", "Egito"),
    ("SLV", "El Salvador"),
    ("ARE", "Emirados Árabes Unidos"),
    ("ECU", "Equador"),
    ("ERI", "Eritreia"),
    ("SVK", "Eslováquia"),
    ("SVN", "Eslovênia"),
    ("ESP", "Espanha"),
    ("USA", "Estados Unidos"),
    ("EST", "Estônia"),
    ("SWZ", "Essuatíni"),
    ("ETH", "Etiópia"),
    ("FJI", "Fiji"),
    ("PHL", "Filipinas"),
    ("FIN", "Finlândia"),
    ("FRA", "França"),
    ("GAB", "Gabão"),
    ("GMB", "Gâmbia"),
    ("GHA", "Gana"),
    ("GEO", "Geórgia"),
    ("GRD", "Granada"),
    ("GRC", "Grécia"),
    ("GTM", "Guatemala"),
    ("GUY", "Guiana"),
    ("GIN", "Guiné"),
    ("GNB", "Guiné-Bissau"),
    ("GNQ", "Guiné Equatorial"),
    ("HTI", "Haiti"),
    ("HND", "Honduras"),
    ("HUN", "Hungria"),
    ("YEM", "Iêmen"),
    ("MHL", "Ilhas Marshall"),
    ("SLB", "Ilhas Salomão"),
    ("IND", "Índia"),
    ("IDN", "Indonésia"),
    ("IRN", "Irã"),
    ("IRQ", "Iraque"),
    ("IRL", "Irlanda"),
    ("ISL", "Islândia"),
    ("ISR", "Israel"),
    ("ITA", "Itália"),
    ("JAM", "Jamaica"),
    ("JPN", "Japão"),
    ("JOR", "Jordânia"),
    ("KIR", "Kiribati"),
    ("KWT", "Kuwait"),
    ("LAO", "Laos"),
    ("LSO", "Lesoto"),
    ("LVA", "Letônia"),
    ("LBN", "Líbano"),
    ("LBR", "Libéria"),
    ("LBY", "Líbia"),
    ("LIE", "Liechtenstein"),
    ("LTU", "Lituânia"),
    ("LUX", "Luxemburgo"),
    ("MKD", "Macedônia do Norte"),
    ("MDG", "Madagascar"),
    ("MYS", "Malásia"),
    ("MWI", "Malawi"),
    ("MDV", "Maldivas"),
    ("MLI", "Mali"),
    ("MLT", "Malta"),
    ("MAR", "Marrocos"),
    ("MUS", "Maurício"),
    ("MRT", "Mauritânia"),
    ("MEX", "México"),
    ("FSM", "Micronésia"),
    ("MOZ", "Moçambique"),
    ("MDA", "Moldávia"),
    ("MCO", "Mônaco"),
    ("MNG", "Mongólia"),
    ("MNE", "Montenegro"),
    ("NAM", "Namíbia"),
    ("NRU", "Nauru"),
    ("NPL", "Nepal"),
    ("NIC", "Nicarágua"),
    ("NER", "Níger"),
    ("NGA", "Nigéria"),
    ("NOR", "Noruega"),
    ("NZL", "Nova Zelândia"),
    ("OMN", "Omã"),
    ("NLD", "Países Baixos"),
    ("PLW", "Palau"),
    ("PAN", "Panamá"),
    ("PNG", "Papua-Nova Guiné"),
    ("PAK", "Paquistão"),
    ("PRY", "Paraguai"),
    ("PER", "Peru"),
    ("POL", "Polônia"),
    ("PRT", "Portugal"),
    ("KEN", "Quênia"),
    ("KGZ", "Quirguistão"),
    ("GBR", "Reino Unido"),
    ("CAF", "República Centro-Africana"),
    ("CZE", "República Tcheca"),
    ("DOM", "República Dominicana"),
    ("ROU", "Romênia"),
    ("RWA", "Ruanda"),
    ("RUS", "Rússia"),
    ("WSM", "Samoa"),
    ("SMR", "San Marino"),
    ("LCA", "Santa Lúcia"),
    ("STP", "São Tomé e Príncipe"),
    ("VCT", "São Vicente e Granadinas"),
    ("SEN", "Senegal"),
    ("SLE", "Serra Leoa"),
    ("SRB", "Sérvia"),
    ("SYC", "Seicheles"),
    ("SGP", "Singapura"),
    ("SYR", "Síria"),
    ("SOM", "Somália"),
    ("LKA", "Sri Lanka"),
    ("ZAF", "África do Sul"),
    ("SDN", "Sudão"),
    ("SSD", "Sudão do Sul"),
    ("SWE", "Suécia"),
    ("CHE", "Suíça"),
    ("SUR", "Suriname"),
    ("THA", "Tailândia"),
    ("TJK", "Tajiquistão"),
    ("TZA", "Tanzânia"),
    ("TLS", "Timor-Leste"),
    ("TGO", "Togo"),
    ("TON", "Tonga"),
    ("TTO", "Trinidad e Tobago"),
    ("TUN", "Tunísia"),
    ("TKM", "Turcomenistão"),
    ("TUR", "Turquia"),
    ("TUV", "Tuvalu"),
    ("UKR", "Ucrânia"),
    ("UGA", "Uganda"),
    ("URY", "Uruguai"),
    ("UZB", "Uzbequistão"),
    ("VUT", "Vanuatu"),
    ("VAT", "Vaticano"),
    ("VEN", "Venezuela"),
    ("VNM", "Vietnã"),
    ("ZMB", "Zâmbia"),
    ("ZWE", "Zimbábue"),
)


class Actor(models.Model):
    name = models.CharField(max_length=200)
    age = models.IntegerField()
    genre = models.ForeignKey(
        Genre, on_delete=models.PROTECT, related_name="genre_actor"
    )
    nationality = models.CharField(
        max_length=100, choices=NATIONALITY_CHOICES, blank=True, null=True
    )

    def __str__(self):
        return str(self.name)
