# Generated by Django 6.0.3 on 2026-03-14 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="start",
            new_name="stars",
        ),
    ]
