# Generated by Django 6.0.3 on 2026-03-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_rename_start_review_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="commented_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
