# Generated by Django 6.0.3 on 2026-03-13 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actors", "0001_initial"),
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="age",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actor",
            name="genre",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="genre_actor",
                to="genres.genre",
            ),
        ),
    ]
