# Generated by Django 6.0.3 on 2026-03-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actors", "0002_actor_age_actor_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="nationality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USA", "Estados Unidos"),
                    ("BRAZIL", "Brasil"),
                    ("ARG", "Argentina"),
                    ("RUS", "Rússia"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
